name: Code Coverage (*nix)

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Install
        run: |
          npm install --ignore-scripts

      # We do not check coverage requirements here because the goal is to
      # generate a report to upload as an artifact.
      - name: Generate coverage report
        run: |
          npm run coverage:ci

      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        if: ${{ success() }}
        with:
          name: coverage-report-nix
          path: ./coverage/lcov-report/

      # Here, we verify the coverage thresholds so that this workflow can pass
      # or fail and stop further workflows if this one fails.
      - name: Verify coverage meets thresholds
        run: |
          npm run coverage:ci-check-coverage
