name: integration

on:
  push:
    branches:
     - main
     - master
     - next
     - 'v*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

permissions:
  contents: read

jobs:
  install-production:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    
    strategy:
      matrix:
        node-version: [16, 18, 20]
        os: [ubuntu-latest]
        pnpm-version: [8]
        # pnpm@8 does not support Node.js 14 so include it separately
        include:
          - node-version: 14
            os: ubuntu-latest
            pnpm-version: 7

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          persist-credentials: false
      
      - name: Use Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Pnpm
        uses: pnpm/action-setup@0b715c7ebbf3cf2174d1386336c5f6d3d8d5504a # v2.3.0
        with:
          version: ${{ matrix.pnpm-version }}
      
      - name: Install Production
        run: |
          pnpm install --prod

      - name: Run server
        run: |
          node integration/server.js &

      - name: Test
        if: ${{ success() }}
        run: |
          bash integration/test.sh
