name: Internal Links Check

on:
  pull_request:
    paths:
      - 'docs/**'
      - '*.md'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Check out repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          persist-credentials: false

      # It will be possible to check only for the links in the changed files
      # See: https://github.com/lycheeverse/lychee-action/issues/17
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@ec3ed119d4f44ad2673a7232460dc7dff59d2421
        with:
          fail: true
          # As external links behaviour is not predictable, we check only internal links
          # to ensure consistency.
          # See: https://github.com/lycheeverse/lychee-action/issues/17#issuecomment-1162586751
          args: --offline --verbose --no-progress './**/*.md'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
