name: Lint Docs

on:
  push:
    branches-ignore:
      - master
      - main
    paths:
       - "**/*.md"
  pull_request:
    branches:
      - master
      - main
    paths:
       - "**/*.md"

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    name: Lint Markdown
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          persist-credentials: false
        
      - name: Setup Node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 'lts/*'

      - name: Install Linter
        run: npm install --ignore-scripts

      - name: Add Matcher
        uses: xt0rted/markdownlint-problem-matcher@98d94724052d20ca2e06c091f202e4c66c3c59fb

      - name: Run Linter
        run: ./node_modules/.bin/markdownlint-cli2

