name: Test compare
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

permissions:
  contents: read

jobs:
  run:
    if: contains(github.event.pull_request.labels.*.name, 'test-compare')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Test compare
        uses: nearform-actions/github-action-test-compare@3d801892864ded1149471fe8f8a167f59f939ebc # v1.0.17
        with:
          label: test-compare
          testCommand: 'npm run test:ci'
