name: website

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '**.md'
  release:
    types:
      - released

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Build website
        run: |
          gh workflow run ci-cd.yml -R fastify/website
    env:
      GH_TOKEN: ${{ secrets.GHA_WEBSITE_FINE_TOKEN }}
